### ISSUE TITLE
Not Getting email notifications after banning !

### ISSUE THREAD

**Issue by nrasakatla** [chef-cookbooks/fail2ban#26]
Hi , 

I'm able to recieve fail2ban start and stop notifications but i'm not able to get email notification when it is banning the ip address .

Please can you help me out on this ?

Thanks,
Naveen

**Comment by ouafnico** [comment]
Hello

Are you using in jail.local, action action = %(action_mw)s or action = %(action_mwl)s ?

I'm using mwl, and if I don't restart after somedays fail2ban, I lost mail notifications too for IP banned (work after restart).

**Comment by cheeseplus** [comment]
Closing this one due to age but please open a new issue with distro specifics and a current reproduction case.
