### ISSUE TITLE
Remove unused "syslog tunables"

### ISSUE THREAD

**Issue by josephholsten** [chef-cookbooks/fail2ban#31]
The attributes `fail2ban.syslog_target` & `fail2ban.syslog_facility` respectively set `syslog-target` & `syslog-facility` in the `fail2ban.conf` template.

I'm skeptical they do anything. [`fail2ban/server/server.py:378`](https://github.com/fail2ban/fail2ban/blob/debian/0.9.1-1/fail2ban/server/server.py#L378) indicates this is hardcoded to the `daemon` facility. I also have no idea what the `syslog-target` line could be about.

Unless there is an actual use for them, they should be removed.

**Comment by iennae** [comment]
@josephholsten Thanks for reporting. I think the current cookbook is not following the right conventions in some cases. It's basically taking the default fail2ban.conf and turning it into a template and making everything an interface to be set/configured. The attributes are straight up from that templatized fail2ban.conf.
