### ISSUE TITLE
Fail2ban 2.3.0 fails with Service Enable

### ISSUE THREAD

**Issue by idistech** [chef-cookbooks/fail2ban#34]
Fail2ban cookbook ( and Chef::Provider::Service ) assumes Upstart for Ubuntu , but from 15.10 fail2ban uses systemd now .. the cookbook adds the wrong entries and seems to break fail2ban installation..

Fix, remove and purge fail2ban

I then added the following to the cookbook ( end of the default.rb )

service 'fail2ban' do
  supports [:status => true, :restart => true]
  action [:enable, :start]

  if platform?('ubuntu') && node['platform_version'].to_f >= 15.10
    provider Chef::Provider::Service::Systemd
  end

  if (platform?('ubuntu') && node['platform_version'].to_f < 12.04) ||
     (platform?('debian') && node['platform_version'].to_f < 7)
    # status command returns non-0 value only since fail2ban 0.8.6-3 (Debian)
    status_command "/etc/init.d/fail2ban status | grep -q 'is running'"
  end
end

Happy to propose a change, if someone can give a newbie a pointer or two

**Comment by iennae** [comment]
@idistech Take a look at version 4.0.0 of this cookbook. It should resolve the problems that you are seeing.
