### ISSUE TITLE
Changing the log level not possible anymore

### ISSUE THREAD

**Issue by aried3r** [chef-cookbooks/fail2ban#46]
In version 4.0 of this cookbook it's [impossible to change](https://github.com/chef-cookbooks/fail2ban/blob/v4.0.0/templates/default/fail2ban.conf.erb#L20) the log level of fail2ban. In version 3.1.0 of this cookbook it was possible to [change it](https://github.com/chef-cookbooks/fail2ban/blob/v3.1.0/templates/default/fail2ban.conf.erb#L20) but it was removed.

Is there a reason why?

At least for Ubuntu 16.04 LTS which has [version 0.9.3](http://packages.ubuntu.com/xenial/fail2ban) of fail2ban you can set the log level using one of [these values](https://github.com/fail2ban/fail2ban/blob/0.9/config/fail2ban.conf#L14-L24).

Ubuntu 14.04 LTS seems to use [0.8.x](http://packages.ubuntu.com/trusty/fail2ban) where the values are [different](https://github.com/fail2ban/fail2ban/blob/0.8/config/fail2ban.conf#L14-L22).

Does that mean that Ubuntu 14.04 is not supported anymore after version 4.0 of this cookbook?

**Comment by iennae** [comment]
No, it means that we spent some time debugging why this wasn't working across the different platforms and got it to a "fixed" state. We need to revisit this and add back the ability to change the log level. As you've documented it is different across different platforms.
