### ISSUE TITLE
Service enable and start doesn't work on Fedora

### ISSUE THREAD

**Issue by john65** [chef-cookbooks/fail2ban#48]
### Cookbook version
4.0.1

### Chef-client version
13.6.4

### Platform Details
Fedora 27

### Scenario:
Start and enable fail2ban

### Steps to Reproduce:
Run on Fedora 27 

### Expected Result:
Run should enable and start fail2ban

### Actual Result:
Doesn't start or enable due to platform_family not matching in recipes/default.rb

    service 'fail2ban' do
      supports [status: true, restart: true]
      action [:enable, :start] if platform_family?('rhel')
      action [:enable] if platform_family?('debian')
    end

Adding `fedora` as a platform_family in my wrapper cookbook fixed it. 

    ohai | grep platform_family
    [2018-01-07T21:31:23+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
    "platform_family": "fedora",

**Comment by tas50** [comment]
This has been fixed in #56
